# Generated by Django 2.0.1 on 2018-01-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('comment', models.TextField()),
                ('unit_cost', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('total_cost', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
